update config

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -87,6 +87,7 @@ jobs:
           echo "WHEEL_CUDA_VERSION=${WHEEL_CUDA_VERSION}" >> $GITHUB_ENV
           echo "MATRIX_PYTHON_VERSION=${MATRIX_PYTHON_VERSION}" >> $GITHUB_ENV
           echo "TORCH_CUDA_VERSION=${TORCH_CUDA_VERSION}" >> $GITHUB_ENV
+          echo "BUILD_MAX_JOBS=$([ "$MATRIX_CUDA_VERSION" == "129" ] && echo 1 || echo 2)" >> $GITHUB_ENV
 
       - name: Free up disk space
         if: ${{ runner.os == 'Linux' }}
@@ -154,18 +155,22 @@ jobs:
           CIBW_BUILD_VERBOSITY: 3
           CIBW_MANYLINUX_X86_64_IMAGE: "quay.io/pypa/manylinux_2_28_x86_64"
           CIBW_BUILD: "cp${{ env.MATRIX_PYTHON_VERSION }}-*"
-          CIBW_ENVIRONMENT: "FLASH_ATTENTION_FORCE_BUILD=TRUE FLASH_ATTENTION_FORCE_CXX11_ABI=${{ matrix.cxx11_abi }} MATRIX_CUDA_VERSION=${{ env.MATRIX_CUDA_VERSION }} MATRIX_TORCH_VERSION=${{ env.MATRIX_TORCH_VERSION }} WHEEL_CUDA_VERSION=${{ env.WHEEL_CUDA_VERSION }} MATRIX_PYTHON_VERSION=${{ env.MATRIX_PYTHON_VERSION }} TORCH_CUDA_VERSION=${{ env.TORCH_CUDA_VERSION }}"
+          CIBW_ENVIRONMENT: "FLASH_ATTENTION_FORCE_BUILD=TRUE FLASH_ATTENTION_FORCE_CXX11_ABI=${{ matrix.cxx11_abi }} MATRIX_CUDA_VERSION=${{ env.MATRIX_CUDA_VERSION }} MATRIX_TORCH_VERSION=${{ env.MATRIX_TORCH_VERSION }} WHEEL_CUDA_VERSION=${{ env.WHEEL_CUDA_VERSION }} MATRIX_PYTHON_VERSION=${{ env.MATRIX_PYTHON_VERSION }} TORCH_CUDA_VERSION=${{ env.TORCH_CUDA_VERSION }} MAX_JOBS=${{ env.BUILD_MAX_JOBS }} NVCC_THREADS=2 "
+
           CIBW_BEFORE_ALL: |
             set -x
             dnf config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/cuda-rhel8.repo
             dnf clean all
-            dnf -y install cuda-toolkit
+            until dnf -y install cuda-toolkit; do
+              echo "Retrying CUDA installation..."
+              sleep 10
+            done
             ls -al /usr/local
             export PATH=$PATH:/usr/local/cuda/bin
             nvcc --version
             # Install PyTorch ${{ matrix.torch-version }}+cu${{ matrix.cuda-version }}
             pip install --upgrade pip
-            python -c "from pip._internal.models.target_python import TargetPython; target_python = TargetPython(); print('\n'.join(map(str, target_python.get_sorted_tags())));"
+
             # With python 3.13 and torch 2.5.1, unless we update typing-extensions, we get error
             # AttributeError: attribute '__default__' of 'typing.ParamSpec' objects is not writable
             pip install typing-extensions==4.12.2
@@ -184,23 +189,20 @@ jobs:
             else
               pip install --no-cache-dir torch==${{ matrix.torch-version }} --index-url https://download.pytorch.org/whl/cu${TORCH_CUDA_VERSION}
             fi
+            # We want setuptools >= 49.6.0 otherwise we can't compile the extension if system CUDA version is 11.7 and pytorch cuda version is 11.6
+            # https://github.com/pytorch/pytorch/blob/664058fa83f1d8eede5d66418abff6e20bd76ca8/torch/utils/cpp_extension.py#L810
+            # However this still fails so I'm using a newer version of setuptools
+            pip install setuptools==75.8.0
+            pip install ninja packaging wheel
+            export PATH=/usr/local/cuda/bin:/usr/local/cuda/lib64:/usr/local/nvidia/bin:/usr/local/nvidia/lib64:$PATH
+            export LD_LIBRARY_PATH=/usr/local/nvidia/lib64:/usr/local/cuda/lib64:$LD_LIBRARY_PATH
             nvcc --version
             python --version
             python -c "import torch; print('PyTorch:', torch.__version__)"
             python -c "import torch; print('CUDA:', torch.version.cuda)"
             python -c "from torch.utils import cpp_extension; print (cpp_extension.CUDA_HOME)"
         run: |
-          set -x
-          # We want setuptools >= 49.6.0 otherwise we can't compile the extension if system CUDA version is 11.7 and pytorch cuda version is 11.6
-          # https://github.com/pytorch/pytorch/blob/664058fa83f1d8eede5d66418abff6e20bd76ca8/torch/utils/cpp_extension.py#L810
-          # However this still fails so I'm using a newer version of setuptools
-          pip install setuptools==75.8.0
-          pip install ninja packaging wheel
-          export PATH=/usr/local/cuda/bin:/usr/local/cuda/lib64:/usr/local/nvidia/bin:/usr/local/nvidia/lib64:$PATH
-          export LD_LIBRARY_PATH=/usr/local/nvidia/lib64:/usr/local/cuda/lib64:$LD_LIBRARY_PATH
-          # Limit MAX_JOBS otherwise the github runner goes OOM
-          # nvcc 11.8 can compile with 2 jobs, but nvcc 12.3 goes OOM
-          MAX_JOBS=$([ "$MATRIX_CUDA_VERSION" == "129" ] && echo 1 || echo 2) NVCC_THREADS=2 FLASH_ATTENTION_FORCE_BUILD="TRUE" FLASH_ATTENTION_FORCE_CXX11_ABI=${{ matrix.cxx11_abi}} python -m cibuildwheel --output-dir=dist
+          python -m cibuildwheel --output-dir=dist
           tmpname=cu${WHEEL_CUDA_VERSION}torch${MATRIX_TORCH_VERSION}cxx11abi${{ matrix.cxx11_abi }}
           wheel_name=$(ls dist/*whl | xargs -n 1 basename | sed "s/-/+$tmpname-/2")
           ls dist/*whl |xargs -I {} mv {} dist/${wheel_name}
